### ISSUE TITLE
Mention extensive Help built into Spirit

### ISSUE THREAD

**Issue by oliverpeter** [jfreyss/spirit#2]
Joël,

I suggest you mention that Spirit has an extensive built-in manual on the GitHub site.

At the moment, people have to download and install the software before they can read it. Although this is really easy thanks to webstart, it represents a hurdle if someone is not sure it is worth the hassle. So it would be good if an online version of the documentation was accessible, too.

Oliver.

**Comment by oliverpeter** [comment]
We should also update the 2-Pager describing the software:

[SPIRIT Software Overview v-2-1.pdf](https://github.com/jfreyss/spirit/files/408568/SPIRIT.Software.Overview.v-2-1.pdf)

Oliver.

**Comment by jfreyss** [comment]
This will be added in the coming version, on the github pages. Hopefully this week.
